import type { Metadata } from "next";
import "./globals.css";
import { Titillium_Web } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import { UserProvider } from "@/Context/contextUser";
import FloatingWhatsApp from "@/Components/FloatingWsp/FloatingWsp";
import Script from 'next/script'; // Importa el componente Script

const titillium = Titillium_Web({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-titillium",
});

export const metadata: Metadata = {
  title: "AB Automotores",
  description: "Generated by Pablo Fernandez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Script de Tailwind CDN reemplazado por el componente Script */}
        <Script 
          src="https://cdn.tailwindcss.com"
          strategy="afterInteractive" // Carga el script después de que la página esté interactiva
        />
      </head>
      <body
        className={`${titillium.className} flex flex-col min-h-screen antialiased`}
      >
        <UserProvider>
          <Navbar />
          {children}
          <FloatingWhatsApp />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
