import type { Metadata } from "next";
import "./globals.css";
import { Titillium_Web } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import { UserProvider } from "@/Context/contextUser";
import FloatingWhatsApp from "@/Components/FloatingWsp/FloatingWsp";
import TailwindInitializer from "@/Components/TailwindInitializer/TailwindInitializer";

const titillium = Titillium_Web({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-titillium",
});

export const metadata: Metadata = {
  title: "AB Automotores",
  description: "Generated by Pablo Fernandez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`invisible ${titillium.className} flex flex-col min-h-screen antialiased`}
      >
        <UserProvider>
          {/* Componente que maneja el hook */}
          <TailwindInitializer />
          <Navbar />
          {children}
          <FloatingWhatsApp />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
